# Runs after merge to main

trigger:
  - main
  - feature/R20-22-azure-piplines

variables:
  - group: radius-angular
  - name: projectName
    value: $[variables.PROJECT_NAME]
  - name: feedName
    value: $[variables.FEED_NAME]
  - name: personalAccessToken
    value: $[variables.PERSONAL_ACCESS_TOKEN]
  - name: orgName
    value: $[variables.ORG_NAME]
  - name: GitHubToken
    value: $[variables.GH_TOKEN]
  - name: npm_config_cache
    value: $(Pipeline.Workspace)/.npm

jobs:
  - job: install_build_publish
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "14.x"
        displayName: "Install Node"

      - task: Bash@3
        displayName: "Install, Lint and Test"
        inputs:
          targetType: "inline"
          script: |
            npm ci --ignore-scripts
            npm run lint
            npm run test

      - task: Bash@3
        displayName: "Generate .npmrc"
        env:
          PERSONAL_ACCESS_TOKEN: $(personalAccessToken)
          FEED_NAME: $(feedName)
          $ORG_NAME: $(orgName)
        inputs:
          targetType: "inline"
          script: |
            chmod +x ./npmrc.sh
            ./npmrc.sh

      - task: npmAuthenticate@0
        displayName: "Authenticate with npm"
        inputs:
          workingFile: .npmrc
          customEndpoint: azureSubscription

      - task: Bash@3
        displayName: "Build and package design system"
        inputs:
          targetType: "inline"
          script: |
            npm run build:ds
            npm run prepare
            cd dist
            npm pack

      - publish: $(System.DefaultWorkingDirectory)
        displayName: "Publish to pipeline artifact dir"
        artifact: "**/*.tgz"

      - script: npm publish
