# Runs after merge to main

trigger:
  - main

variables:
  - group: radius-angular
  - name: projectName
    value: $[variables.PROJECT_NAME]
  - name: feedName
    value: $[variables.FEED_NAME]
  - name: personalAccessToken
    value: $[variables.PERSONAL_ACCESS_TOKEN]
  - name: orgName
    value: $[variables.ORG_NAME]
  - name: GitHubToken
    value: $[variables.GH_TOKEN]
  - name: npmToken
    value: $[variables.NPM_TOKEN]

jobs:
  - job: install_build_publish
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Install Node'

      - task: Bash@3
        displayName: 'Install, Lint and Test'
        inputs:
          targetType: 'inline'
          script: |
            npm ci --ignore-scripts
            npm run lint
            npm run test

      - task: Bash@3
        displayName: 'Generate .npmrc'
        env:
          PERSONAL_ACCESS_TOKEN: $(personalAccessToken)
          FEED_NAME: $(feedName)
          ORG_NAME: $(orgName)
          NPM_TOKEN: $(npmToken)
        inputs:
          targetType: 'inline'
          script: |
            chmod +x ./npmrc.sh
            ./npmrc.sh

      - task: npmAuthenticate@0
        displayName: 'Authenticate with npm'
        inputs:
          workingFile: .npmrc
          customEndpoint: azureSubscription

      - task: Bash@3
        displayName: 'Build, pack and version design system'
        inputs:
          targetType: 'inline'
          script: |
            npm run build:ds
            cd dist/ds
            npm --no-git-tag-version version patch
            npm pack

      - task: Npm@1
        displayName: 'Publish to Azure Devops org artifact registry'
        inputs:
          command: publish
          publishRegistry: useFeed
          publishFeed: $(projectName)/$(feedName)
          workingDir: dist/ds
        continueOnError: true
