# runs on pull requests
trigger: none

# Environment variables
variables:
  - group: radius-angular
  - name: CHROMATIC_PROJECT_TOKEN
    value: $[variables.CHROMATIC_PROJECT_TOKEN]
# triggers on pull requests against the following branches
pr:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node"

  - script: npm ci --ignore-script
    condition: ne(variables.CACHE_RESTORED, 'true')
    displayName: "cache exists; Node clean install"

  - task: Bash@3
    displayName: "Lint and Test"
    inputs:
      targetType: "inline"
      script: |
        npm run lint
        npm run test

  - task: Bash@3
    displayName: "Dry run of packaging"
    inputs:
      targetType: "inline"
      script: |
        npm run build:ds
        cd dist/ds
        npm pack --dry-run
  - task: CmdLine@2
    displayName: Publish to Chromatic
    inputs:
      # Runs Chromatic
      script: npx chromatic --project-token=$(CHROMATIC_PROJECT_TOKEN) --exit-zero-on-changes
